In [20]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [21]:
import numpy as np
import pandas as pd
import pickle
import warnings

from scipy import stats

# Ignore all warnings
warnings.filterwarnings('ignore')

In [22]:
with open('../results_guards_regression.pkl', 'rb') as f:
    results = pickle.load(f)

In [23]:
base_names = ['LIME', 'SHAP', 'CE', 'PCE', 'CE Guarded', 'CE Unguarded', 'PCE Guarded', 'PCE Unguarded']
norm_names = ['', ' Dist', ' Std', ' Abs', ' Var']
setup_names = {'lime_base': 'LIME Base', 'shap_base': 'SHAP Base'}
for i, base in enumerate(['lime', 'shap', 'ce', 'pce', 'ce_guarded', 'ce_unguarded', 'pce_guarded', 'pce_unguarded']):
    for j, setup in enumerate(['']):#['', '_dist', '_std', '_abs', '_var']
        setup_names[base + setup] = base_names[i] + norm_names[j]
setup_names

{'lime_base': 'LIME Base',
 'shap_base': 'SHAP Base',
 'lime': 'LIME',
 'shap': 'SHAP',
 'ce': 'CE',
 'pce': 'PCE',
 'ce_guarded': 'CE Guarded',
 'ce_unguarded': 'CE Unguarded',
 'pce_guarded': 'PCE Guarded',
 'pce_unguarded': 'PCE Unguarded'}

In [24]:
results.keys()
filtered_results = {k: v for k, v in results.items() if k not in ['num_rep', 'test_size',]}
filtered_results.keys()

dict_keys(['abalone', 'anacalt', 'bank8fh', 'bank8fm', 'bank8nh', 'bank8nm', 'comp', 'concreate', 'deltaA', 'deltaE', 'friedm', 'kin8fh', 'kin8fm', 'kin8nh', 'kin8nm', 'laser', 'mg', 'mortage', 'plastic', 'puma8fh', 'puma8fm', 'puma8nh', 'puma8nm'])

In [26]:

stab_data = []
rob_data = []
for key in filtered_results.keys():
    for setup in filtered_results[key]['RF']['rob_timer'].keys():
        stab_data.append([key, setup_names[setup], np.mean(filtered_results[key]['RF']['stab_timer'][setup])])
        rob_data.append([key, setup_names[setup], np.mean(filtered_results[key]['RF']['rob_timer'][setup])])

stab_df = pd.DataFrame(stab_data, columns=['Dataset', 'Setup', 'Value'])
rob_df = pd.DataFrame(rob_data, columns=['Dataset', 'Setup', 'Value'])
stab_df

     Dataset          Setup     Value
0    abalone      LIME Base  0.065040
1    abalone      SHAP Base  0.200513
2    abalone           LIME  0.079421
3    abalone           SHAP  0.278086
4    abalone             CE  0.004079
..       ...            ...       ...
225  puma8nm            PCE  0.006562
226  puma8nm     CE Guarded  0.005746
227  puma8nm   CE Unguarded  0.002466
228  puma8nm    PCE Guarded  0.008000
229  puma8nm  PCE Unguarded  0.005111

[230 rows x 3 columns]

In [27]:
import pandas as pd
import numpy as np

# Assuming stab_df and rob_df are already defined

# Define the order of the 'Setup' column
setup_order = stab_df['Setup'].unique()  # or specify the order explicitly: ['Setup1', 'Setup2', ...]

# Convert 'Setup' column to categorical with the specified order
stab_df['Setup'] = pd.Categorical(stab_df['Setup'], categories=setup_order, ordered=True)
rob_df['Setup'] = pd.Categorical(rob_df['Setup'], categories=setup_order, ordered=True)

stab_pivot = stab_df.pivot(index='Dataset', columns='Setup', values='Value')
rob_pivot = rob_df.pivot(index='Dataset', columns='Setup', values='Value')

display(stab_pivot) 
display(stab_df.pivot_table(columns='Setup', values=['Value'], aggfunc=[np.mean]))
display(rob_pivot)
display(rob_df.pivot_table(columns='Setup', values=['Value'], aggfunc=[np.mean]))
stab_pivot.to_csv('stab_time.csv')
rob_pivot.to_csv('rob_time.csv')

Setup,LIME Base,SHAP Base,LIME,SHAP,CE,PCE,CE Guarded,CE Unguarded,PCE Guarded,PCE Unguarded
Dataset,,,,,,,,,,
abalone,0.065040,0.200513,0.079421,0.278086,0.004079,0.005901,0.004258,0.001295,0.006003,0.003510
anacalt,0.032525,0.031940,0.045248,0.049300,0.002682,0.003683,0.002561,0.000691,0.004101,0.002092
bank8fh,0.104942,0.262035,0.125076,0.345914,0.004287,0.006951,0.004951,0.001720,0.006205,0.003927
bank8fm,0.098105,0.238498,0.113195,0.313035,0.004173,0.007195,0.004562,0.001801,0.007165,0.003962
bank8nh,0.111829,0.271680,0.129278,0.355813,0.005266,0.006796,0.004776,0.001815,0.007095,0.004399
bank8nm,0.100596,0.258179,0.118271,0.333875,0.004246,0.006453,0.005243,0.001831,0.006570,0.003679
comp,0.088305,0.611087,0.105896,0.778925,0.005589,0.008858,0.006114,0.002064,0.009285,0.005420
concreate,0.061150,0.142325,0.076495,0.218149,0.003407,0.005328,0.003412,0.001075,0.005533,0.003008
deltaA,0.109892,0.051570,0.129286,0.064880,0.002815,0.004299,0.002854,0.001229,0.004729,0.003790
deltaE,0.131125,0.069713,0.149162,0.087688,0.003172,0.004855,0.003448,0.001522,0.006427,0.004311
friedm,0.090507,0.040107,0.110049,0.053807,0.002606,0.004531,0.002711,0.001582,0.003622,0.002232
kin8fh,0.105103,0.288758,0.128677,0.379050,0.004286,0.007231,0.004617,0.001973,0.008292,0.004508
kin8fm,0.111912,0.278548,0.120818,0.370205,0.004430,0.007496,0.004828,0.001993,0.006992,0.004927
kin8nh,0.105374,0.281104,0.120884,0.363192,0.004498,0.007461,0.004533,0.002596,0.006829,0.004293
kin8nm,0.104063,0.274197,0.121849,0.361193,0.004071,0.007167,0.005521,0.001648,0.006889,0.005398
laser,0.070172,0.023875,0.083746,0.030954,0.001875,0.003721,0.001859,0.000637,0.002793,0.001665
mg,0.092795,0.057659,0.107918,0.079859,0.002691,0.004256,0.003294,0.001014,0.004101,0.002312
mortage,0.071895,0.378435,0.087049,0.559802,0.006408,0.009161,0.006716,0.001660,0.008879,0.004625
plastic,0.052490,0.018089,0.067398,0.019464,0.001270,0.002047,0.001217,0.000579,0.001808,0.001502
puma8fh,0.112221,0.286909,0.127657,0.370402,0.004705,0.006940,0.005047,0.001863,0.007209,0.005527
puma8fm,0.105280,0.264157,0.121349,0.344257,0.004343,0.007075,0.004421,0.002625,0.006472,0.004271
puma8nh,0.109458,0.272802,0.120760,0.364593,0.004292,0.007793,0.004266,0.001768,0.007714,0.004476
puma8nm,0.105974,0.246912,0.126498,0.351810,0.004466,0.006562,0.005746,0.002466,0.008000,0.005111

           mean                                                               \
Setup LIME Base SHAP Base      LIME      SHAP        CE       PCE CE Guarded
Value  0.093076   0.21083  0.109391  0.281489  0.003898  0.006163   0.004215


Setup CE Unguarded PCE Guarded PCE Unguarded
Value     0.001628    0.006205      0.003867

Setup,LIME Base,SHAP Base,LIME,SHAP,CE,PCE,CE Guarded,CE Unguarded,PCE Guarded,PCE Unguarded
Dataset,,,,,,,,,,
abalone,0.062666,0.181401,0.075311,0.256528,0.003274,0.005243,0.003335,0.001106,0.005038,0.002915
anacalt,0.032227,0.027427,0.048514,0.045092,0.002440,0.003926,0.002481,0.000665,0.003829,0.001912
bank8fh,0.131982,3.960876,0.127384,0.367467,0.004290,0.007233,0.004136,0.001712,0.007376,0.004026
bank8fm,0.106010,0.235022,0.117020,0.318894,0.004531,0.006285,0.004455,0.002783,0.007151,0.003881
bank8nh,0.108192,0.272174,0.125266,0.355352,0.004287,0.006341,0.004418,0.001701,0.006918,0.003917
bank8nm,0.103383,0.258451,0.120454,0.344326,0.004828,0.006480,0.004909,0.001789,0.006920,0.004943
comp,0.089706,0.617164,0.105465,0.796573,0.005833,0.009163,0.006018,0.002175,0.009960,0.004571
concreate,0.061838,0.146384,0.078808,0.226420,0.003499,0.005088,0.003875,0.001143,0.005642,0.003201
deltaA,0.113618,0.052274,0.124680,0.065016,0.002675,0.003987,0.002602,0.001191,0.004804,0.002895
deltaE,0.135822,0.069466,0.153883,0.085357,0.003527,0.004758,0.004275,0.001421,0.005036,0.004426
friedm,0.091329,0.040737,0.106926,0.052129,0.002402,0.003906,0.002931,0.000923,0.003927,0.002201
kin8fh,0.106897,0.287887,0.129846,0.370534,0.004762,0.006524,0.004815,0.002973,0.006826,0.004455
kin8fm,0.103324,0.269814,0.120537,0.352934,0.004450,0.008432,0.005128,0.001941,0.007773,0.004121
kin8nh,0.105859,0.277735,0.123112,0.358406,0.005234,0.009383,0.005306,0.001942,0.008223,0.004783
kin8nm,0.103877,0.276601,0.122259,0.359042,0.004433,0.006611,0.004284,0.002710,0.007060,0.005413
laser,0.071170,0.026269,0.087022,0.032005,0.001751,0.002983,0.001875,0.000660,0.003078,0.001879
mg,0.094825,0.058271,0.111998,0.079196,0.002702,0.004109,0.003038,0.001077,0.004663,0.002451
mortage,0.070934,0.389041,0.096210,0.592837,0.007337,0.011051,0.007687,0.002055,0.010695,0.006028
plastic,0.050997,0.016705,0.066539,0.018755,0.001161,0.001874,0.001180,0.000560,0.001765,0.001171
puma8fh,0.116534,0.285586,0.138660,0.376416,0.004424,0.007840,0.005060,0.002036,0.008616,0.004475
puma8fm,0.113480,0.252147,0.139177,0.369895,0.004718,0.007834,0.004588,0.001921,0.008449,0.004713
puma8nh,0.109540,0.272787,0.127075,0.359992,0.004506,0.008234,0.004511,0.001978,0.008069,0.004409
puma8nm,0.107020,0.267661,0.126128,0.353033,0.004423,0.007025,0.005724,0.001893,0.007246,0.004712

           mean                                                               \
Setup LIME Base SHAP Base      LIME      SHAP        CE       PCE CE Guarded
Value  0.095271  0.371386  0.111838  0.284183  0.003978  0.006274   0.004201


Setup CE Unguarded PCE Guarded PCE Unguarded
Value     0.001668    0.006481      0.003804

In [28]:
stab = 'Stability'
rob = 'Robustness'

dataset = {}
for key in filtered_results.keys():
    stability = filtered_results[key]['RF']['stability']
    robustness = filtered_results[key]['RF']['robustness']

    performance = {
        stab: {},
        rob: {},
        'Prediction Variance': np.mean(
            [
                np.var(
                    [
                        robustness['predict'][i][j]
                        for i in range(len(robustness['predict']))
                    ]
                )
                for j in range(len(robustness['predict'][0]))
            ]
        ),
    }
    try:
        for setup in stability.keys():
            # Get the most important feature for each instance using the absolute value of the feature weights
            stab_feature = []
            rob_feature = []
            for j in range(len(stability[setup][0])): # number of instances        
                stab_feature.append([np.argmax(np.abs(stability[setup][i][j]['predict'])) for i in range(len(stability[setup]))])
                rob_feature.append([np.argmax(np.abs(robustness[setup][i][j]['predict'])) for i in range(len(robustness[setup]))])
            stab_feature = stats.mode(stab_feature, axis=1)
            rob_feature = stats.mode(rob_feature, axis=1)


            performance[stab][setup_names[setup]] = np.mean([np.var([stability[setup][i][j]['predict'][stab_feature.mode[j]] for i in range(len(stability[setup]))]) for j in range(len(stability[setup][0]))])
            performance[rob][setup_names[setup]] = np.mean([np.var([robustness[setup][i][j]['predict'][rob_feature.mode[j]] for i in range(len(robustness[setup]))]) for j in range(len(robustness[setup][0]))])
    except:
        print(setup, robustness[setup])
        
    dataset[key] = performance

dataset

{'abalone': {'Stability': {'LIME Base': 8.239784003441834e-06,
   'SHAP Base': 9.14816723583937e-36,
   'LIME': 8.055769344191291e-06,
   'SHAP': 1.9018558200823955e-35,
   'CE': 5.585196838722984e-35,
   'PCE': 1.5407439555097887e-35,
   'CE Guarded': 5.585196838722984e-35,
   'CE Unguarded': 0.0,
   'PCE Guarded': 1.5407439555097887e-35,
   'PCE Unguarded': 0.0},
  'Robustness': {'LIME Base': 0.0008339648233842419,
   'SHAP Base': 0.00014012043723724918,
   'LIME': 0.0009112083137154322,
   'SHAP': 0.00014012043723724918,
   'CE': 0.00235845426303855,
   'PCE': 0.01889238291852353,
   'CE Guarded': 0.00235845426303855,
   'CE Unguarded': 1.4890306122449605e-05,
   'PCE Guarded': 0.01889238291852353,
   'PCE Unguarded': 0.004081723904766137},
  'Prediction Variance': 7.971418367346933e-05},
 'anacalt': {'Stability': {'LIME Base': 2.0864669787353068e-05,
   'SHAP Base': 1.6370404527291504e-34,
   'LIME': 2.0085542843751156e-05,
   'SHAP': 1.6370404527291504e-34,
   'CE': 3.0814879110195774e-35,
   'PCE': 2.465190328815662e-33,
   'CE Guarded': 3.0814879110195774e-35,
   'CE Unguarded': 0.0,
   'PCE Guarded': 2.465190328815662e-33,
   'PCE Unguarded': 3.274080905458301e-35},
  'Robustness': {'LIME Base': 0.006777460025138879,
   'SHAP Base': 0.00018263245648470053,
   'LIME': 0.00677694754234803,
   'SHAP': 0.00018263245648470053,
   'CE': 0.01787200738893939,
   'PCE': 0.04909463155617535,
   'CE Guarded': 0.01787200738893939,
   'CE Unguarded': 0.0,
   'PCE Guarded': 0.04909463155617535,
   'PCE Unguarded': 0.006727105392459091},
  'Prediction Variance': 4.5548920944452465e-05},
 'bank8fh': {'Stability': {'LIME Base': 1.3252000984895933e-05,
   'SHAP Base': 7.763905088311045e-35,
   'LIME': 1.2520822517892321e-05,
   'SHAP': 9.388908478887775e-36,
   'CE': 6.355568816477879e-35,
   'PCE': 3.6977854932234927e-34,
   'CE Guarded': 6.355568816477879e-35,
   'CE Unguarded': 0.0,
   'PCE Guarded': 3.6977854932234927e-34,
   'PCE Unguarded': 1.3096323621833205e-34},
  'Robustness': {'LIME Base': 0.0007031520911549338,
   'SHAP Base': 8.647708620676505e-05,
   'LIME': 0.0006720893926338582,
   'SHAP': 8.647708620676499e-05,
   'CE': 0.006506303159535151,
   'PCE': 0.015639275736085364,
   'CE Guarded': 0.006506303159535151,
   'CE Unguarded': 2.6818728742527067e-05,
   'PCE Guarded': 0.015639275736085364,
   'PCE Unguarded': 0.0027683968133544877},
  'Prediction Variance': 8.361217283943359e-05},
 'bank8fm': {'Stability': {'LIME Base': 1.7776560894518403e-05,
   'SHAP Base': 6.608347121678703e-35,
   'LIME': 1.6765986469226563e-05,
   'SHAP': 4.1557957081230825e-35,
   'CE': 8.474091755303838e-35,
   'PCE': 1.5407439555097888e-34,
   'CE Guarded': 8.474091755303838e-35,
   'CE Unguarded': 0.0,
   'PCE Guarded': 1.5407439555097888e-34,
   'PCE Unguarded': 3.6977854932234927e-34},
  'Robustness': {'LIME Base': 0.0012014311227259193,
   'SHAP Base': 8.417014731951041e-05,
   'LIME': 0.0011912747376418098,
   'SHAP': 8.41701473195103e-05,
   'CE': 0.0028934300180064897,
   'PCE': 0.018644005389585282,
   'CE Guarded': 0.0028934300180064897,
   'CE Unguarded': 3.2423394545519605e-05,
   'PCE Guarded': 0.018644005389585282,
   'PCE Unguarded': 0.0019227282571625747},
  'Prediction Variance': 2.2118192619090885e-05},
 'bank8nh': {'Stability': {'LIME Base': 6.097252074000206e-06,
   'SHAP Base': 1.5287068933573685e-35,
   'LIME': 6.540965193314391e-06,
   'SHAP': 4.2731570641091793e-35,
   'CE': 4.622231866529366e-35,
   'PCE': 1.0014835710813627e-34,
   'CE Guarded': 4.622231866529366e-35,
   'CE Unguarded': 0.0,
   'PCE Guarded': 1.0014835710813627e-34,
   'PCE Unguarded': 0.0},
  'Robustness': {'LIME Base': 0.0002837847079147504,
   'SHAP Base': 3.805206463214796e-05,
   'LIME': 0.00028925455471515117,
   'SHAP': 3.8052064632148e-05,
   'CE': 0.0073613456007355395,
   'PCE': 0.01671925400598919,
   'CE Guarded': 0.0073613456007355395,
   'CE Unguarded': 4.3006312024628894e-05,
   'PCE Guarded': 0.01671925400598919,
   'PCE Unguarded': 0.0152553303328986},
  'Prediction Variance': 0.00013200570674004011},
 'bank8nm': {'Stability': {'LIME Base': 8.6923441830757e-06,
   'SHAP Base': 3.7796375158599505e-35,
   'LIME': 9.357834619401543e-06,
   'SHAP': 8.425943506694156e-36,
   'CE': 5.777789833161707e-35,
   'PCE': 3.0814879110195774e-35,
   'CE Guarded': 5.777789833161707e-35,
   'CE Unguarded': 8.125016952883652e-37,
   'PCE Guarded': 3.0814879110195774e-35,
   'PCE Unguarded': 0.0},
  'Robustness': {'LIME Base': 0.0003920429858972705,
   'SHAP Base': 5.2576965855683e-05,
   'LIME': 0.00040193955340718436,
   'SHAP': 5.257696585568299e-05,
   'CE': 0.0025362345405710502,
   'PCE': 0.0044914968016009195,
   'CE Guarded': 0.0025362345405710502,
   'CE Unguarded': 5.891994079513296e-07,
   'PCE Guarded': 0.0044914968016009195,
   'PCE Unguarded': 0.0007307522783299366},
  'Prediction Variance': 2.8160171803507938e-05},
 'comp': {'Stability': {'LIME Base': 1.3085842205559442e-05,
   'SHAP Base': 2.420268746423807e-07,
   'LIME': 1.187390559042325e-05,
   'SHAP': 2.420268746423796e-07,
   'CE': 1.232595164407831e-34,
   'PCE': 3.851859888774472e-35,
   'CE Guarded': 1.232595164407831e-34,
   'CE Unguarded': 0.0,
   'PCE Guarded': 3.851859888774472e-35,
   'PCE Unguarded': 5.7176045223996065e-37},
  'Robustness': {'LIME Base': 0.004688797330967491,
   'SHAP Base': 9.490629931644358e-05,
   'LIME': 0.0046864978914051125,
   'SHAP': 9.490629931644347e-05,
   'CE': 0.004054683236404448,
   'PCE': 0.030113915756488314,
   'CE Guarded': 0.004054683236404448,
   'CE Unguarded': 6.26705438220628e-05,
   'PCE Guarded': 0.030113915756488314,
   'PCE Unguarded': 0.0010456670073671062},
  'Prediction Variance': 9.603052749719285e-06},
 'concreate': {'Stability': {'LIME Base': 1.575426031058328e-05,
   'SHAP Base': 2.2148194360453213e-35,
   'LIME': 1.5593163486326745e-05,
   'SHAP': 1.4444474582904268e-35,
   'CE': 1.232595164407831e-34,
   'PCE': 6.162975822039155e-34,
   'CE Guarded': 1.232595164407831e-34,
   'CE Unguarded': 0.0,
   'PCE Guarded': 6.162975822039155e-34,
   'PCE Unguarded': 1.4637067577342993e-34},
  'Robustness': {'LIME Base': 0.00023111149761927108,
   'SHAP Base': 0.00010994327390742414,
   'LIME': 0.00023846319957154956,
   'SHAP': 0.00010994327390742357,
   'CE': 0.006250857915970402,
   'PCE': 0.029748272286988783,
   'CE Guarded': 0.006250857915970402,
   'CE Unguarded': 1.3661325519834558e-06,
   'PCE Guarded': 0.029748272286988783,
   'PCE Unguarded': 0.007187968819272917},
  'Prediction Variance': 0.00034337164682991757},
 'deltaA': {'Stability': {'LIME Base': 1.9364608310590178e-06,
   'SHAP Base': 3.250006781153461e-36,
   'LIME': 1.5674847857668282e-06,
   'SHAP': 3.611118645726067e-36,
   'CE': 1.925929944387236e-35,
   'PCE': 1.1401505270772436e-33,
   'CE Guarded': 1.925929944387236e-35,
   'CE Unguarded': 0.0,
   'PCE Guarded': 1.1401505270772436e-33,
   'PCE Unguarded': 1.3866695599588098e-34},
  'Robustness': {'LIME Base': 5.8978870915757e-05,
   'SHAP Base': 9.809367113779142e-06,
   'LIME': 5.9626768052641514e-05,
   'SHAP': 9.809367113779218e-06,
   'CE': 0.00011666108527131844,
   'PCE': 0.017854680459395138,
   'CE Guarded': 0.00011666108527131844,
   'CE Unguarded': 9.370470524608645e-06,
   'PCE Guarded': 0.017854680459395138,
   'PCE Unguarded': 0.00965384862746526},
  'Prediction Variance': 2.1681600865332643e-05},
 'deltaE': {'Stability': {'LIME Base': 2.044606415574714e-06,
   'SHAP Base': 5.657419211637505e-36,
   'LIME': 1.9828721157047533e-06,
   'SHAP': 4.6944542394438876e-36,
   'CE': 1.1555579666323415e-35,
   'PCE': 6.162975822039155e-34,
   'CE Guarded': 1.1555579666323415e-35,
   'CE Unguarded': 0.0,
   'PCE Guarded': 6.162975822039155e-34,
   'PCE Unguarded': 5.392603844284261e-35},
  'Robustness': {'LIME Base': 0.0001138977706273824,
   'SHAP Base': 2.099557125785737e-05,
   'LIME': 0.00011373107813921783,
   'SHAP': 2.0995571257857395e-05,
   'CE': 0.0002537731748209139,
   'PCE': 0.012573890636952006,
   'CE Guarded': 0.0002537731748209139,
   'CE Unguarded': 1.5371742112485117e-05,
   'PCE Guarded': 0.012573890636952006,
   'PCE Unguarded': 0.005809002911585703},
  'Prediction Variance': 2.87394238683128e-05},
 'friedm': {'Stability': {'LIME Base': 1.1261929501484558e-05,
   'SHAP Base': 2.311115933264683e-35,
   'LIME': 1.0677143978243212e-05,
   'SHAP': 1.4925957069001078e-35,
   'CE': 8.08890576642639e-35,
   'PCE': 6.7214955059114535e-34,
   'CE Guarded': 8.08890576642639e-35,
   'CE Unguarded': 0.0,
   'PCE Guarded': 6.7214955059114535e-34,
   'PCE Unguarded': 3.0814879110195774e-35},
  'Robustness': {'LIME Base': 0.000417864204031517,
   'SHAP Base': 7.249317811206152e-05,
   'LIME': 0.00046779482485371295,
   'SHAP': 7.249317811206162e-05,
   'CE': 0.002564327628974052,
   'PCE': 0.024496906396256245,
   'CE Guarded': 0.002564327628974052,
   'CE Unguarded': 6.823546484045675e-06,
   'PCE Guarded': 0.024496906396256245,
   'PCE Unguarded': 0.006098390196513431},
  'Prediction Variance': 0.0002220894522892144},
 'kin8fh': {'Stability': {'LIME Base': 6.051889317983703e-06,
   'SHAP Base': 4.9351954824922916e-36,
   'LIME': 6.607208841442913e-06,
   'SHAP': 8.666684749742561e-36,
   'CE': 1.1555579666323415e-35,
   'PCE': 2.7155612215860024e-34,
   'CE Guarded': 1.1555579666323415e-35,
   'CE Unguarded': 0.0,
   'PCE Guarded': 2.7155612215860024e-34,
   'PCE Unguarded': 2.9370431651905346e-35},
  'Robustness': {'LIME Base': 0.00012629226310570597,
   'SHAP Base': 2.63035384079666e-05,
   'LIME': 0.00012114999787352199,
   'SHAP': 2.630353840796677e-05,
   'CE': 0.0006249034021280843,
   'PCE': 0.014032779675963948,
   'CE Guarded': 0.0006249034021280843,
   'CE Unguarded': 1.389714049153009e-05,
   'PCE Guarded': 0.014032779675963948,
   'PCE Unguarded': 0.0066603567751052075},
  'Prediction Variance': 6.456791881882497e-05},
 'kin8fm': {'Stability': {'LIME Base': 7.923264880716933e-06,
   'SHAP Base': 1.396299209680746e-35,
   'LIME': 8.427996758683622e-06,
   'SHAP': 1.5888922041194697e-35,
   'CE': 2.1185229388259594e-35,
   'PCE': 6.472629245910165e-34,
   'CE Guarded': 2.1185229388259594e-35,
   'CE Unguarded': 0.0,
   'PCE Guarded': 6.472629245910165e-34,
   'PCE Unguarded': 1.0014835710813627e-34},
  'Robustness': {'LIME Base': 0.00012965303999420413,
   'SHAP Base': 3.524434429798516e-05,
   'LIME': 0.00014242636298667478,
   'SHAP': 3.524434429798513e-05,
   'CE': 0.0004529580249570637,
   'PCE': 0.010194174149496001,
   'CE Guarded': 0.0004529580249570637,
   'CE Unguarded': 2.4729752108173016e-06,
   'PCE Guarded': 0.010194174149496001,
   'PCE Unguarded': 0.0061016944008917525},
  'Prediction Variance': 3.177781223071727e-05},
 'kin8nh': {'Stability': {'LIME Base': 6.202007820226824e-06,
   'SHAP Base': 1.5888922041194697e-35,
   'LIME': 7.419927409302553e-06,
   'SHAP': 2.455560679093726e-35,
   'CE': 4.044452883213195e-35,
   'PCE': 2.1570415377137044e-34,
   'CE Guarded': 4.044452883213195e-35,
   'CE Unguarded': 0.0,
   'PCE Guarded': 2.1570415377137044e-34,
   'PCE Unguarded': 5.392603844284261e-35},
  'Robustness': {'LIME Base': 0.0005449863883746673,
   'SHAP Base': 8.4411883075837e-05,
   'LIME': 0.0005649296843851197,
   'SHAP': 8.441188307583692e-05,
   'CE': 0.0033750376016989875,
   'PCE': 0.027182204686825404,
   'CE Guarded': 0.0033750376016989875,
   'CE Unguarded': 2.2153331920527928e-05,
   'PCE Guarded': 0.027182204686825404,
   'PCE Unguarded': 0.006523852824407577},
  'Prediction Variance': 0.00016953375037721046},
 'kin8nm': {'Stability': {'LIME Base': 1.0539766655421939e-05,
   'SHAP Base': 1.5407439555097887e-35,
   'LIME': 8.671645324233814e-06,
   'SHAP': 1.2037062152420224e-35,
   'CE': 1.1555579666323415e-34,
   'PCE': 9.244463733058732e-34,
   'CE Guarded': 1.1555579666323415e-34,
   'CE Unguarded': 0.0,
   'PCE Guarded': 9.244463733058732e-34,
   'PCE Unguarded': 6.162975822039155e-35},
  'Robustness': {'LIME Base': 0.0004281463974076292,
   'SHAP Base': 0.0001927187062144068,
   'LIME': 0.0004619408752899397,
   'SHAP': 0.0001927187062144072,
   'CE': 0.002422678592680663,
   'PCE': 0.020064444144576497,
   'CE Guarded': 0.002422678592680663,
   'CE Unguarded': 1.564300307088499e-05,
   'PCE Guarded': 0.020064444144576497,
   'PCE Unguarded': 0.01427196183219763},
  'Prediction Variance': 0.000129214494446733},
 'laser': {'Stability': {'LIME Base': 1.0922033003581074e-05,
   'SHAP Base': 3.4185256512873435e-35,
   'LIME': 9.196642077683657e-06,
   'SHAP': 1.925929944387236e-35,
   'CE': 5.970382827600431e-35,
   'PCE': 4.08297148210094e-34,
   'CE Guarded': 5.970382827600431e-35,
   'CE Unguarded': 0.0,
   'PCE Guarded': 4.08297148210094e-34,
   'PCE Unguarded': 6.162975822039155e-35},
  'Robustness': {'LIME Base': 0.0005203764702271098,
   'SHAP Base': 9.78903488470187e-05,
   'LIME': 0.0005182118053651029,
   'SHAP': 9.78903488470188e-05,
   'CE': 0.007521848404972449,
   'PCE': 0.03281776534646362,
   'CE Guarded': 0.007521848404972449,
   'CE Unguarded': 8.089802383698459e-05,
   'PCE Guarded': 0.03281776534646362,
   'PCE Unguarded': 0.006794336509716219},
  'Prediction Variance': 0.00014876677831603217},
 'mg': {'Stability': {'LIME Base': 1.7694258822613465e-05,
   'SHAP Base': 2.7083389842945504e-35,
   'LIME': 1.4913930618052308e-05,
   'SHAP': 3.1777844082389393e-35,
   'CE': 1.5600032549536611e-34,
   'PCE': 4.930380657631324e-34,
   'CE Guarded': 1.5600032549536611e-34,
   'CE Unguarded': 4.81482486096809e-37,
   'PCE Guarded': 4.930380657631324e-34,
   'PCE Unguarded': 6.96945898625131e-35},
  'Robustness': {'LIME Base': 0.0006628973326674102,
   'SHAP Base': 0.0001447518044720298,
   'LIME': 0.0006412172268327461,
   'SHAP': 0.00014475180447203048,
   'CE': 0.0020824199558019097,
   'PCE': 0.01594950711890693,
   'CE Guarded': 0.0020824199558019097,
   'CE Unguarded': 3.319875449018518e-05,
   'PCE Guarded': 0.01594950711890693,
   'PCE Unguarded': 0.0038276501537554304},
  'Prediction Variance': 0.00037448819925962136},
 'mortage': {'Stability': {'LIME Base': 6.685823391971499e-06,
   'SHAP Base': 5.224708874278254e-07,
   'LIME': 6.939808785468029e-06,
   'SHAP': 5.224708874278145e-07,
   'CE': 7.896312771987667e-35,
   'PCE': 7.703719777548943e-34,
   'CE Guarded': 7.896312771987667e-35,
   'CE Unguarded': 0.0,
   'PCE Guarded': 7.703719777548943e-34,
   'PCE Unguarded': 4.81482486096809e-37},
  'Robustness': {'LIME Base': 0.001081529359045386,
   'SHAP Base': 8.315288173586876e-05,
   'LIME': 0.0010931121892956428,
   'SHAP': 8.315288173586868e-05,
   'CE': 0.0010055553005313934,
   'PCE': 0.0011080761188311202,
   'CE Guarded': 0.0010055553005313934,
   'CE Unguarded': 1.0208081964609669e-06,
   'PCE Guarded': 0.0011080761188311202,
   'PCE Unguarded': 0.004270318724840128},
  'Prediction Variance': 1.2825545262898526e-05},
 'plastic': {'Stability': {'LIME Base': 8.154960817717177e-05,
   'SHAP Base': 2.69630192214213e-34,
   'LIME': 6.652608269029662e-05,
   'SHAP': 4.005934284325451e-34,
   'CE': 6.471124613141112e-34,
   'PCE': 2.588449845256445e-33,
   'CE Guarded': 6.471124613141112e-34,
   'CE Unguarded': 0.0,
   'PCE Guarded': 2.588449845256445e-33,
   'PCE Unguarded': 1.232595164407831e-34},
  'Robustness': {'LIME Base': 0.0018323722869687852,
   'SHAP Base': 0.002218505217237346,
   'LIME': 0.0018940183285299933,
   'SHAP': 0.0022185052172373422,
   'CE': 0.0942589110299088,
   'PCE': 0.10260106723947782,
   'CE Guarded': 0.0942589110299088,
   'CE Unguarded': 0.00010907367765180514,
   'PCE Guarded': 0.10260106723947782,
   'PCE Unguarded': 0.0110106879722221},
  'Prediction Variance': 0.0012736725640007127},
 'puma8fh': {'Stability': {'LIME Base': 1.175662722091614e-05,
   'SHAP Base': 2.744450170751811e-35,
   'LIME': 1.175681758561091e-05,
   'SHAP': 6.740754805355325e-35,
   'CE': 1.232595164407831e-34,
   'PCE': 3.774822690998982e-34,
   'CE Guarded': 1.232595164407831e-34,
   'CE Unguarded': 0.0,
   'PCE Guarded': 3.774822690998982e-34,
   'PCE Unguarded': 4.237045877651919e-35},
  'Robustness': {'LIME Base': 0.00046951712328951263,
   'SHAP Base': 0.0003189126734954239,
   'LIME': 0.00047825005202650024,
   'SHAP': 0.0003189126734954244,
   'CE': 0.0035835881144614984,
   'PCE': 0.016783329794787055,
   'CE Guarded': 0.0035835881144614984,
   'CE Unguarded': 3.2254487778869196e-05,
   'PCE Guarded': 0.016783329794787055,
   'PCE Unguarded': 0.009379553441337401},
  'Prediction Variance': 0.00018203797697757555},
 'puma8fm': {'Stability': {'LIME Base': 2.857839144240645e-05,
   'SHAP Base': 1.4107436842636503e-34,
   'LIME': 2.5775511336162265e-05,
   'SHAP': 9.437056727497456e-35,
   'CE': 2.7733391199176195e-34,
   'PCE': 1.8257815872790997e-33,
   'CE Guarded': 2.7733391199176195e-34,
   'CE Unguarded': 0.0,
   'PCE Guarded': 1.8257815872790997e-33,
   'PCE Unguarded': 3.8759340130793125e-34},
  'Robustness': {'LIME Base': 0.002848532672780655,
   'SHAP Base': 0.0009053438255782603,
   'LIME': 0.002791751493995428,
   'SHAP': 0.0009053438255782598,
   'CE': 0.006786341690877444,
   'PCE': 0.02454649006484869,
   'CE Guarded': 0.006786341690877444,
   'CE Unguarded': 9.633816273606614e-06,
   'PCE Guarded': 0.02454649006484869,
   'PCE Unguarded': 0.010091183277238189},
  'Prediction Variance': 4.957840995710692e-05},
 'puma8nh': {'Stability': {'LIME Base': 2.2020120269998993e-05,
   'SHAP Base': 3.4666738998970244e-35,
   'LIME': 1.9880877255542337e-05,
   'SHAP': 4.4777871207003236e-35,
   'CE': 3.813341289886727e-34,
   'PCE': 2.04148574105047e-33,
   'CE Guarded': 3.813341289886727e-34,
   'CE Unguarded': 0.0,
   'PCE Guarded': 2.04148574105047e-33,
   'PCE Unguarded': 8.474091755303838e-35},
  'Robustness': {'LIME Base': 0.001250499105849685,
   'SHAP Base': 0.00014796529714019918,
   'LIME': 0.0011858096542238052,
   'SHAP': 0.00014796529714019893,
   'CE': 0.002851444560211111,
   'PCE': 0.017915667865947994,
   'CE Guarded': 0.002851444560211111,
   'CE Unguarded': 4.5153572467643384e-05,
   'PCE Guarded': 0.017915667865947994,
   'PCE Unguarded': 0.009490700465509132},
  'Prediction Variance': 0.0001686804012668177},
 'puma8nm': {'Stability': {'LIME Base': 3.518180171624343e-05,
   'SHAP Base': 5.007417855406813e-35,
   'LIME': 3.1972907623562324e-05,
   'SHAP': 8.100942828578811e-35,
   'CE': 6.240013019814645e-34,
   'PCE': 1.9490411037198825e-33,
   'CE Guarded': 6.240013019814645e-34,
   'CE Unguarded': 0.0,
   'PCE Guarded': 1.9490411037198825e-33,
   'PCE Unguarded': 5.546678239835239e-34},
  'Robustness': {'LIME Base': 0.0013734309822020078,
   'SHAP Base': 0.0003179767328167146,
   'LIME': 0.0013276621203053762,
   'SHAP': 0.0003179767328167153,
   'CE': 0.004376427012206951,
   'PCE': 0.01355723804895531,
   'CE Guarded': 0.004376427012206951,
   'CE Unguarded': 8.963932236397379e-05,
   'PCE Guarded': 0.01355723804895531,
   'PCE Unguarded': 0.007396661019794479},
  'Prediction Variance': 3.192998864273564e-05}}

In [29]:
stab_data = []
rob_data = []
for key in dataset.keys():
    for setup in dataset[key][stab].keys():
        stab_data.append([key, setup, dataset[key][stab][setup]])
        rob_data.append([key, setup, dataset[key][rob][setup]])
    rob_data.append([key, 'Prediction Variance', dataset[key]['Prediction Variance']])

stab_df = pd.DataFrame(stab_data, columns=['Dataset', 'Setup', 'Value'])
rob_df = pd.DataFrame(rob_data, columns=['Dataset', 'Setup', 'Value'])
display(rob_df)

     Dataset                Setup     Value
0    abalone            LIME Base  0.000834
1    abalone            SHAP Base  0.000140
2    abalone                 LIME  0.000911
3    abalone                 SHAP  0.000140
4    abalone                   CE  0.002358
..       ...                  ...       ...
248  puma8nm           CE Guarded  0.004376
249  puma8nm         CE Unguarded  0.000090
250  puma8nm          PCE Guarded  0.013557
251  puma8nm        PCE Unguarded  0.007397
252  puma8nm  Prediction Variance  0.000032

[253 rows x 3 columns]

In [30]:
import pandas as pd
import numpy as np

# Assuming stab_df and rob_df are already defined

# Convert 'Setup' column to categorical with the specified order
stab_df['Setup'] = pd.Categorical(stab_df['Setup'], categories=stab_df['Setup'].dropna().unique(), ordered=True)
rob_df['Setup'] = pd.Categorical(rob_df['Setup'], categories=rob_df['Setup'].dropna().unique(), ordered=True)

stab_pivot = stab_df.pivot(index='Dataset', columns='Setup', values='Value')
rob_pivot = rob_df.pivot(index='Dataset', columns='Setup', values='Value')

display(stab_pivot) 
display(stab_df.pivot_table(columns='Setup', values=['Value'], aggfunc=[np.mean]))
display(rob_pivot)
display(rob_df.pivot_table(columns='Setup', values=['Value'], aggfunc=[np.mean]))
stab_pivot.to_csv('stability.csv')
rob_pivot.to_csv('robustness.csv')

Setup,LIME Base,SHAP Base,LIME,SHAP,CE,PCE,CE Guarded,CE Unguarded,PCE Guarded,PCE Unguarded
Dataset,,,,,,,,,,
abalone,0.000008,9.148167e-36,0.000008,1.901856e-35,5.585197e-35,1.540744e-35,5.585197e-35,0.000000e+00,1.540744e-35,0.000000e+00
anacalt,0.000021,1.637040e-34,0.000020,1.637040e-34,3.081488e-35,2.465190e-33,3.081488e-35,0.000000e+00,2.465190e-33,3.274081e-35
bank8fh,0.000013,7.763905e-35,0.000013,9.388908e-36,6.355569e-35,3.697785e-34,6.355569e-35,0.000000e+00,3.697785e-34,1.309632e-34
bank8fm,0.000018,6.608347e-35,0.000017,4.155796e-35,8.474092e-35,1.540744e-34,8.474092e-35,0.000000e+00,1.540744e-34,3.697785e-34
bank8nh,0.000006,1.528707e-35,0.000007,4.273157e-35,4.622232e-35,1.001484e-34,4.622232e-35,0.000000e+00,1.001484e-34,0.000000e+00
bank8nm,0.000009,3.779638e-35,0.000009,8.425944e-36,5.777790e-35,3.081488e-35,5.777790e-35,8.125017e-37,3.081488e-35,0.000000e+00
comp,0.000013,2.420269e-07,0.000012,2.420269e-07,1.232595e-34,3.851860e-35,1.232595e-34,0.000000e+00,3.851860e-35,5.717605e-37
concreate,0.000016,2.214819e-35,0.000016,1.444447e-35,1.232595e-34,6.162976e-34,1.232595e-34,0.000000e+00,6.162976e-34,1.463707e-34
deltaA,0.000002,3.250007e-36,0.000002,3.611119e-36,1.925930e-35,1.140151e-33,1.925930e-35,0.000000e+00,1.140151e-33,1.386670e-34
deltaE,0.000002,5.657419e-36,0.000002,4.694454e-36,1.155558e-35,6.162976e-34,1.155558e-35,0.000000e+00,6.162976e-34,5.392604e-35
friedm,0.000011,2.311116e-35,0.000011,1.492596e-35,8.088906e-35,6.721496e-34,8.088906e-35,0.000000e+00,6.721496e-34,3.081488e-35
kin8fh,0.000006,4.935195e-36,0.000007,8.666685e-36,1.155558e-35,2.715561e-34,1.155558e-35,0.000000e+00,2.715561e-34,2.937043e-35
kin8fm,0.000008,1.396299e-35,0.000008,1.588892e-35,2.118523e-35,6.472629e-34,2.118523e-35,0.000000e+00,6.472629e-34,1.001484e-34
kin8nh,0.000006,1.588892e-35,0.000007,2.455561e-35,4.044453e-35,2.157042e-34,4.044453e-35,0.000000e+00,2.157042e-34,5.392604e-35
kin8nm,0.000011,1.540744e-35,0.000009,1.203706e-35,1.155558e-34,9.244464e-34,1.155558e-34,0.000000e+00,9.244464e-34,6.162976e-35
laser,0.000011,3.418526e-35,0.000009,1.925930e-35,5.970383e-35,4.082971e-34,5.970383e-35,0.000000e+00,4.082971e-34,6.162976e-35
mg,0.000018,2.708339e-35,0.000015,3.177784e-35,1.560003e-34,4.930381e-34,1.560003e-34,4.814825e-37,4.930381e-34,6.969459e-35
mortage,0.000007,5.224709e-07,0.000007,5.224709e-07,7.896313e-35,7.703720e-34,7.896313e-35,0.000000e+00,7.703720e-34,4.814825e-37
plastic,0.000082,2.696302e-34,0.000067,4.005934e-34,6.471125e-34,2.588450e-33,6.471125e-34,0.000000e+00,2.588450e-33,1.232595e-34
puma8fh,0.000012,2.744450e-35,0.000012,6.740755e-35,1.232595e-34,3.774823e-34,1.232595e-34,0.000000e+00,3.774823e-34,4.237046e-35
puma8fm,0.000029,1.410744e-34,0.000026,9.437057e-35,2.773339e-34,1.825782e-33,2.773339e-34,0.000000e+00,1.825782e-33,3.875934e-34
puma8nh,0.000022,3.466674e-35,0.000020,4.477787e-35,3.813341e-34,2.041486e-33,3.813341e-34,0.000000e+00,2.041486e-33,8.474092e-35
puma8nm,0.000035,5.007418e-35,0.000032,8.100943e-35,6.240013e-34,1.949041e-33,6.240013e-34,0.000000e+00,1.949041e-33,5.546678e-34

           mean                                                      \
Setup LIME Base     SHAP Base      LIME          SHAP            CE
Value  0.000016  3.323903e-08  0.000014  3.323903e-08  1.405929e-34


Setup           PCE    CE Guarded  CE Unguarded   PCE Guarded PCE Unguarded
Value  8.144237e-34  1.405929e-34  5.626018e-38  8.144237e-34  1.075368e-34

Setup,LIME Base,SHAP Base,LIME,SHAP,CE,PCE,CE Guarded,CE Unguarded,PCE Guarded,PCE Unguarded,Prediction Variance
Dataset,,,,,,,,,,,
abalone,0.000834,0.000140,0.000911,0.000140,0.002358,0.018892,0.002358,1.489031e-05,0.018892,0.004082,0.000080
anacalt,0.006777,0.000183,0.006777,0.000183,0.017872,0.049095,0.017872,0.000000e+00,0.049095,0.006727,0.000046
bank8fh,0.000703,0.000086,0.000672,0.000086,0.006506,0.015639,0.006506,2.681873e-05,0.015639,0.002768,0.000084
bank8fm,0.001201,0.000084,0.001191,0.000084,0.002893,0.018644,0.002893,3.242339e-05,0.018644,0.001923,0.000022
bank8nh,0.000284,0.000038,0.000289,0.000038,0.007361,0.016719,0.007361,4.300631e-05,0.016719,0.015255,0.000132
bank8nm,0.000392,0.000053,0.000402,0.000053,0.002536,0.004491,0.002536,5.891994e-07,0.004491,0.000731,0.000028
comp,0.004689,0.000095,0.004686,0.000095,0.004055,0.030114,0.004055,6.267054e-05,0.030114,0.001046,0.000010
concreate,0.000231,0.000110,0.000238,0.000110,0.006251,0.029748,0.006251,1.366133e-06,0.029748,0.007188,0.000343
deltaA,0.000059,0.000010,0.000060,0.000010,0.000117,0.017855,0.000117,9.370471e-06,0.017855,0.009654,0.000022
deltaE,0.000114,0.000021,0.000114,0.000021,0.000254,0.012574,0.000254,1.537174e-05,0.012574,0.005809,0.000029
friedm,0.000418,0.000072,0.000468,0.000072,0.002564,0.024497,0.002564,6.823546e-06,0.024497,0.006098,0.000222
kin8fh,0.000126,0.000026,0.000121,0.000026,0.000625,0.014033,0.000625,1.389714e-05,0.014033,0.006660,0.000065
kin8fm,0.000130,0.000035,0.000142,0.000035,0.000453,0.010194,0.000453,2.472975e-06,0.010194,0.006102,0.000032
kin8nh,0.000545,0.000084,0.000565,0.000084,0.003375,0.027182,0.003375,2.215333e-05,0.027182,0.006524,0.000170
kin8nm,0.000428,0.000193,0.000462,0.000193,0.002423,0.020064,0.002423,1.564300e-05,0.020064,0.014272,0.000129
laser,0.000520,0.000098,0.000518,0.000098,0.007522,0.032818,0.007522,8.089802e-05,0.032818,0.006794,0.000149
mg,0.000663,0.000145,0.000641,0.000145,0.002082,0.015950,0.002082,3.319875e-05,0.015950,0.003828,0.000374
mortage,0.001082,0.000083,0.001093,0.000083,0.001006,0.001108,0.001006,1.020808e-06,0.001108,0.004270,0.000013
plastic,0.001832,0.002219,0.001894,0.002219,0.094259,0.102601,0.094259,1.090737e-04,0.102601,0.011011,0.001274
puma8fh,0.000470,0.000319,0.000478,0.000319,0.003584,0.016783,0.003584,3.225449e-05,0.016783,0.009380,0.000182
puma8fm,0.002849,0.000905,0.002792,0.000905,0.006786,0.024546,0.006786,9.633816e-06,0.024546,0.010091,0.000050
puma8nh,0.001250,0.000148,0.001186,0.000148,0.002851,0.017916,0.002851,4.515357e-05,0.017916,0.009491,0.000169
puma8nm,0.001373,0.000318,0.001328,0.000318,0.004376,0.013557,0.004376,8.963932e-05,0.013557,0.007397,0.000032

           mean                                                               \
Setup LIME Base SHAP Base      LIME      SHAP        CE       PCE CE Guarded
Value  0.001173  0.000238  0.001175  0.000238  0.007918  0.023262   0.007918


Setup CE Unguarded PCE Guarded PCE Unguarded Prediction Variance
Value     0.000029    0.023262       0.00683            0.000159